#!/bin/zsh

dark-mode() {
  if [[ $TERM =~ 'kitty' ]];then
    kitty @ set-colors --all --configured ~/.config/kitty/kitty-themes/themes/Tomorrow_Night_Eighties.conf
  fi

  export BAT_THEME="ansi-dark"
  export FZF_PREVIEW_PREVIEW_BAT_THEME="ansi-dark"

  osascript -e 'tell app "System Events" to tell appearance preferences to set dark mode to true'
}

