#!/usr/bin/env bash
#
# Update to the latest released version of elixir-ls

cd elixir-ls || exit

git fetch --tags
latesttag=$(git describe --tags `git rev-list --tags --max-count=1`)

echo checking out ${latesttag}
git checkout ${latesttag}

echo building release
mix deps.get && mix compile && mix elixir_ls.release -o release
