#!/usr/bin/env bash
#
# Update to the latest released version of elixir-ls

cd elixir-ls || exit

git fetch
latesttag=$(git describe --tags)

echo checking out ${latesttag}
git checkout ${latesttag}

echo building release
mix deps.get && mix compile && mix elixir_ls.release -o release
